name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-test:
    name: Docker Build Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Test Docker build for app
      run: |
        docker build -t robo-boy-app -f Dockerfile.dev .
        echo "✅ App container build successful"

    - name: Test Docker build for ROS stack
      run: |
        docker build -t robo-boy-ros -f Dockerfile.ros .
        echo "✅ ROS stack container build successful"

    - name: Test Docker Compose setup
      run: |
        # Create dummy certs directory and files required by docker-compose
        mkdir -p certs
        touch certs/local-key.pem
        touch certs/local-cert.pem
        
        # Run docker-compose build to test all services
        docker compose build
        echo "✅ Docker Compose build successful" 